version: "2"

services:
  dev:
    image: hseeberger/scala-sbt:11.0.11_1.5.4_2.13.6
    working_dir: /work
    command: sbt
    volumes:
      - .:/work
      - coursier-cache:/root/.cache/coursier
      - docker-scala-sbt-cache:/root/.sbt

volumes:
  coursier-cache:
    external: true
  docker-scala-sbt-cache:
    external: true
